main: com.gmail.markushygedombrowski.HLVagtVault
name: HLVagtVault
version: 1.0
author: Markus Hyge Dombrowski
depend: [Vault,PlaceholderAPI]
commands:
  vagtvault:
    aliases: ["vv"]
    description: VagtVault Command